const $=s=>document.querySelector(s),status=$('#workbench-status');
let assets=[],selected=null,layer='terrain',cursor=0,cells=Array.from({length:160},()=>({terrain:null,unit:null}));
const blobUrls=[];
function image(asset,cls=''){const img=document.createElement('img');img.src=asset.src;img.alt='';img.className=cls;return img;}
function board(){const grid=$('#sandbox');grid.replaceChildren();cells.forEach((cell,i)=>{const button=document.createElement('button');button.className='pixel-cell'+(i===cursor?' cursor':'');button.setAttribute('role','gridcell');button.setAttribute('aria-label',`Tile ${i%16+1}, ${Math.floor(i/16)+1}`);button.tabIndex=i===cursor?0:-1;for(const key of ['terrain','unit']){const asset=assets.find(a=>a.file===cell[key]);if(asset)button.append(image(asset,key==='unit'?'unit-sprite':''));}button.onclick=()=>{cursor=i;paint();};grid.append(button);});$('#coordinates').textContent=`FIELD / ${String(cursor%16+1).padStart(2,'0')} : ${String(Math.floor(cursor/16)+1).padStart(2,'0')}`;$('#layer-indicator').textContent=layer.toUpperCase();}
function gallery(){const term=$('#asset-search').value.toLowerCase();const grid=$('#sprite-grid');grid.replaceChildren();$('#asset-count').textContent=`${assets.length} FILES`;const visible=assets.filter(a=>(a.file+' '+a.source).toLowerCase().includes(term));if(!visible.length){const p=document.createElement('p');p.className='sprite-empty';p.textContent=assets.length?'No sprites match your search.':'No original assets imported yet. Capture a pack on AWBW, then load its ZIP here. The screen stays blank until real artwork is available.';grid.append(p);}for(const asset of visible){const button=document.createElement('button');button.className='sprite'+(selected?.file===asset.file?' selected':'');button.title=asset.file;button.setAttribute('aria-label',`Select ${asset.file.split('/').pop()}`);const img=image(asset);button.append(img);button.onclick=()=>{selected=asset;gallery();const info=$('#sprite-info');info.replaceChildren();const title=document.createElement('strong');title.textContent=asset.file.split('/').pop();const dimensions=document.createElement('div');dimensions.textContent=`${img.naturalWidth} × ${img.naturalHeight} px · ${asset.mime} · ${asset.size.toLocaleString()} bytes`;const link=document.createElement('a');link.href=asset.source;link.target='_blank';link.rel='noopener noreferrer';link.textContent='Original AWBW source ↗';info.append(title,dimensions,link);status.textContent=`Selected ${title.textContent}. Tap the map or press A to place it on the ${layer} layer.`;};grid.append(button);}}
function paint(){if(!selected){status.textContent='Choose a sprite first, then tap a map tile.';board();return;}cells[cursor][layer]=selected.file;board();}
function move(dx,dy){const x=Math.max(0,Math.min(15,cursor%16+dx)),y=Math.max(0,Math.min(9,Math.floor(cursor/16)+dy));cursor=y*16+x;board();}
$('#up').onclick=()=>move(0,-1);$('#down').onclick=()=>move(0,1);$('#left').onclick=()=>move(-1,0);$('#right').onclick=()=>move(1,0);$('#paint').onclick=paint;$('#erase').onclick=()=>{cells[cursor][layer]=null;board();};$('#fill').onclick=()=>{if(!selected||layer!=='terrain'){status.textContent='Select a terrain sprite in the Terrain layer first.';return;}cells.forEach(c=>c.terrain=selected.file);board();};$('#reset').onclick=()=>{cells=cells.map(()=>({terrain:null,unit:null}));board();};$('#asset-search').oninput=gallery;document.querySelectorAll('[data-layer]').forEach(b=>b.onclick=()=>{layer=b.dataset.layer;document.querySelectorAll('[data-layer]').forEach(t=>t.classList.toggle('active',t===b));board();});$('#sandbox').onkeydown=e=>{const moves={ArrowUp:[0,-1],ArrowDown:[0,1],ArrowLeft:[-1,0],ArrowRight:[1,0]};if(moves[e.key]){e.preventDefault();move(...moves[e.key]);$('#sandbox .cursor').focus();}else if(e.key===' '){e.preventDefault();paint();}};
function verify(record){const url=new URL(record.source);if(url.origin!=='https://awbw.amarriner.com')throw new Error('Expected original AWBW asset URLs.');if(!/^assets\/[a-zA-Z0-9._-]+\.(png|gif|jpe?g|svg|webp|avif|bmp)$/i.test(record.file))throw new Error('Invalid asset filename.');}
// The collector generates uncompressed (STORE) ZIP archives; other ZIP formats are rejected explicitly.
async function loadZip(file){if(file.size>70*1024*1024)throw new Error('Pack exceeds 70 MB.');const bytes=new Uint8Array(await file.arrayBuffer()),view=new DataView(bytes.buffer),decoder=new TextDecoder(),files=new Map();let offset=0;while(offset+30<=bytes.length&&view.getUint32(offset,true)===0x04034b50){const flags=view.getUint16(offset+6,true),method=view.getUint16(offset+8,true),size=view.getUint32(offset+18,true),nameSize=view.getUint16(offset+26,true),extra=view.getUint16(offset+28,true),start=offset+30+nameSize+extra,end=start+size;if(method!==0||(flags&9)!==0)throw new Error('Use a ZIP exported by the AWBW collector (uncompressed).');if(end>bytes.length)throw new Error('Truncated asset pack.');const name=decoder.decode(bytes.subarray(offset+30,offset+30+nameSize));files.set(name,bytes.slice(start,end));offset=end;}
 if(!files.has('manifest.json'))throw new Error('No asset manifest in this ZIP.');const manifest=JSON.parse(decoder.decode(files.get('manifest.json')));if(manifest.format!=='field-command-assets-v1'||!Array.isArray(manifest.assets))throw new Error('Unknown pack format.');const result=[];for(const record of manifest.assets){verify(record);const data=files.get(record.file);if(!data||data.length!==record.size)throw new Error('Missing asset or incorrect size.');const hash=Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',data))).map(b=>b.toString(16).padStart(2,'0')).join('');if(hash!==record.sha256)throw new Error('Asset integrity check failed.');result.push({...record,data});}const unique=new Map();for(const record of result){if(unique.has(record.file))continue;const src=URL.createObjectURL(new Blob([record.data],{type:record.mime}));blobUrls.push(src);const{data,...meta}=record;unique.set(record.file,{...meta,src});}assets=[...unique.values()];selected=null;gallery();board();status.textContent=`Loaded ${assets.length} original images. GIF animations are preserved. Choose a sprite to build a scene. This ZIP stays in this browser tab; use the importer to store it in the repository.`;}
$('#pack-input').onchange=async e=>{const file=e.target.files[0];if(!file)return;status.textContent='Reading and verifying asset pack…';try{await loadZip(file);}catch(error){status.textContent='Could not load pack: '+error.message;}e.target.value='';};
async function init(){board();try{const response=await fetch('assets/catalog.json');if(!response.ok)throw new Error('Catalog unavailable.');const catalog=await response.json(),unique=new Map();for(const record of catalog.assets){verify(record);unique.set(record.file,{...record,src:record.file});}assets=[...unique.values()];gallery();status.textContent=assets.length?`Loaded ${assets.length} bundled images. Ready to use—no asset collection or upload needed.`:'No AWBW files downloaded yet. Install the collector on AWBW and load its exported ZIP here.';}catch(error){gallery();status.textContent='Could not read local catalog: '+error.message;}}init();window.addEventListener('beforeunload',()=>blobUrls.forEach(url=>URL.revokeObjectURL(url)));
