// ==UserScript==
// @name         Field Command — AWBW read-only bridge
// @namespace    field-command-awbw-bridge
// @version      0.4.0
// @description  Mirror rendered AWBW sprites into Field Command and export inspection data. Never submits game orders.
// @match        https://awbw.amarriner.com/game.php*
// @grant        none
// @run-at       document-start
// @noframes
// ==/UserScript==
const FC_INSPECTION=(()=>{// Read-only evidence sanitizers shared by the userscript build and local tests.
const secretKey=/auth|token|secret|password|cookie|session|csrf|nonce|signature|hash|email|chat|message|private|account|key/i;
const safeField=/^(?:id|x|y|hp|health|fuel|ammo|army|owner|type|name|capture|movement|moved|attacked|finished|version|turn|day|funds|weather|fog|success|error|status|result|action|unit|player|gameId|stateTime|playerID|unitID|buildingID|attacker|defender|err|Move|Fire|Capt|Build|NextTurn|End|coordinates|destination|path|moves|game|gameData|game_data|data|response|state|units|players|map|terrain|buildings|properties|active_player|current_turn|current_player|(?:games?|units?|players?|maps?|terrain|buildings?)_(?:id|x|y|hp|hit_points|players_id|team|health|fuel|ammo|army|owner|type|name|capture|movement|movement_points|moved|attacked|finished|version|turn|day|funds|fog))$/i;
const safeRequestField=/^(?:x|y|action|type|destination|path|moves|turn|day|gameId|stateTime|playerID|unitID|buildingID|attacker|defender|(?:games?|units?|players?|turn)_(?:id|x|y))$/i;
const enumValue=/^(?:move|fire|capt|end|nextturn|attack|capture|wait|end[ _-]?turn|build|buy|purchase|infantry|mech|tank|md[ ._-]?tank|neotank|megatank|recon|apc|artillery|rocket|missile|anti[ -]?air|b[ -]?copter|t[ -]?copter|fighter|bomber|cruiser|battleship|lander|sub|carrier|plain|forest|mountain|road|bridge|sea|river|city|base|airport|port|hq|snow|rain|clear|fog|success|error|ok|os|ge|bm|yc|bh)$/i;
function schema(value,depth=0){
 if(depth>4)return '…';
 if(Array.isArray(value))return{array:value.length?schema(value[0],depth+1):'empty'};
 if(value&&typeof value==='object'){const out={};for(const key of Object.keys(value).slice(0,80)){if(secretKey.test(key))continue;out[key]=schema(value[key],depth+1);}return out;}
 return value===null?'null':typeof value;
}
function responseSample(value,depth=0){
 if(depth>8)return undefined;
 if(value===null||typeof value==='boolean')return value;
 if(typeof value==='number')return Number.isFinite(value)?value:undefined;
 if(typeof value==='string'){if(/^-?\d+(?:\.\d+)?$/.test(value)&&value.length<16)return value;if(enumValue.test(value))return value;return undefined;}
 if(Array.isArray(value))return value.slice(0,400).map(item=>responseSample(item,depth+1)).filter(item=>item!==undefined);
 if(value&&typeof value==='object'){const out={};for(const key of Object.keys(value).slice(0,500)){if(secretKey.test(key)||(!safeField.test(key)&&!/^\d{1,12}$/.test(key)))continue;const item=responseSample(value[key],depth+1);if(item!==undefined)out[key]=item;}return out;}
 return undefined;
}
function bodyObject(body){
 try{if(body instanceof URLSearchParams)return Object.fromEntries(body);if(typeof FormData!=='undefined'&&body instanceof FormData)return Object.fromEntries([...body].filter(([,v])=>typeof v==='string'));if(typeof body==='string'){return body.trim().startsWith('{')?JSON.parse(body):Object.fromEntries(new URLSearchParams(body));}}catch{}
 return {};
}
function requestSample(body,url){
 const out={};const values={...Object.fromEntries(new URL(url,'https://awbw.amarriner.com').searchParams),...bodyObject(body)};
 for(const[key,value]of Object.entries(values)){if(secretKey.test(key)||!safeRequestField.test(key))continue;const item=responseSample(value);if(item!==undefined)out[key]=item;}
 return out;
}
;return {schema,responseSample,requestSample};})();

(() => {
'use strict';
if(window.top!==window.self||window.__fieldCommandBridge)return;
window.__fieldCommandBridge=true;
const contracts=[];
function path(raw){try{const u=new URL(raw,location.href);return u.origin===location.origin?u.pathname:null;}catch{return null;}}
function fields(body){try{if(body instanceof FormData||body instanceof URLSearchParams)return [...new Set(body.keys())].slice(0,60);if(typeof body==='string'){if(body.trim().startsWith('{'))return Object.keys(JSON.parse(body)).slice(0,60);return [...new Set(new URLSearchParams(body).keys())].slice(0,60);}}catch{}return [];}
function record(url,method,status,keys,responseSchema,requestExample,responseExample){const endpoint=path(url);if(!endpoint)return;const queryFieldNames=[...new Set(new URL(url,location.href).searchParams.keys())].slice(0,60);contracts.push({path:endpoint,method:String(method||'GET').toUpperCase(),status,requestFieldNames:keys,queryFieldNames,responseSchema:responseSchema||null,requestSample:requestExample||{},responseSample:responseExample??null,evidence:'observed-official-page; independent client not tested'});if(contracts.length>150)contracts.shift();}
// Observe requests already issued by AWBW; never initiate an action request.
const originalFetch=window.fetch;
window.fetch=function(input,init){const result=originalFetch.apply(this,arguments);const raw=typeof input==='string'||input instanceof URL?String(input):input.url;const method=init?.method||(input instanceof Request?input.method:'GET'),keys=fields(init?.body),requestExample=FC_INSPECTION.requestSample(init?.body,raw);result.then(response=>{const mime=response.headers.get('content-type')||'';if(mime.includes('json'))response.clone().text().then(text=>{let shape=null,sample=null;try{if(text.length<200000){const data=JSON.parse(text);shape=FC_INSPECTION.schema(data);sample=FC_INSPECTION.responseSample(data);}}catch{}record(raw,method,response.status,keys,shape,requestExample,sample);}).catch(()=>record(raw,method,response.status,keys,null,requestExample));else record(raw,method,response.status,keys,null,requestExample);},()=>record(raw,method,0,keys,null,requestExample));return result;};
const open=XMLHttpRequest.prototype.open,send=XMLHttpRequest.prototype.send,requests=new WeakMap();
XMLHttpRequest.prototype.open=function(method,url){requests.set(this,{method,url});return open.apply(this,arguments);};
XMLHttpRequest.prototype.send=function(body){const info=requests.get(this);if(info)this.addEventListener('loadend',()=>{let shape=null,sample=null;try{const data=this.responseType==='json'?this.response:(this.getResponseHeader('content-type')||'').includes('json')&&this.responseText.length<200000?JSON.parse(this.responseText):null;if(data!==null){shape=FC_INSPECTION.schema(data);sample=FC_INSPECTION.responseSample(data);}}catch{}record(info.url,info.method,this.status,fields(body),shape,FC_INSPECTION.requestSample(body,info.url),sample);},{once:true});return send.apply(this,arguments);};
// AWBW's official client sends orders through WebSocket (game.js emitData).
// Observe native traffic only; this inspector never opens a socket or sends an order.
const NativeWebSocket=window.WebSocket;
if(NativeWebSocket){
 const nativeSend=NativeWebSocket.prototype.send;
 function socketEvidence(socket,direction,payload){try{if(typeof payload!=='string'||payload.length>200000)return;const data=JSON.parse(payload);if(!data||typeof data!=='object')return;const url=new URL(socket.url);contracts.push({transport:'websocket',path:url.pathname,direction,method:direction==='outgoing'?'WS_SEND':'WS_RECEIVE',status:null,requestFieldNames:direction==='outgoing'?Object.keys(data):[],requestSample:direction==='outgoing'?FC_INSPECTION.requestSample(JSON.stringify(data),'https://awbw.amarriner.com/'):{},responseSchema:direction==='incoming'?FC_INSPECTION.schema(data):null,responseSample:direction==='incoming'?FC_INSPECTION.responseSample(data):null,evidence:'observed-official-websocket; not an independently verified order'});if(contracts.length>150)contracts.shift();}catch{}}
 NativeWebSocket.prototype.send=function(payload){socketEvidence(this,'outgoing',payload);return nativeSend.apply(this,arguments);};
 window.WebSocket=new Proxy(NativeWebSocket,{construct(Target,args){const socket=Reflect.construct(Target,args);socket.addEventListener('message',event=>socketEvidence(socket,'incoming',event.data));return socket;}});
}
let host,ui,status,client=null,clientOrigin='',timer,observer,lastError='',lastSent='',connected=false;
const unitPattern=/(?:^|\/)(?:aa|ab|ar|bd|bh|bm|ci|ge|gs|js|ne|os|pc|pl|rf|sc|tg|uw|wn|yc)(?:infantry|mech|tank|md\.tank|neotank|megatank|recon|apc|artillery|rocket|missile|anti-air|b-copter|t-copter|fighter|bomber|stealth|lander|cruiser|battleship|sub|carrier|blackboat|blackbomb|piperunner)\.(gif|png)$/i;
function sourceUrl(raw){try{const u=new URL(raw,location.href);if(u.origin!==location.origin||!u.pathname.startsWith('/terrain/')||!/\.(gif|png|webp|jpe?g)$/i.test(u.pathname))return null;u.search='';u.hash='';return u.href;}catch{return null;}}
function visible(node){const r=node.getBoundingClientRect(),style=getComputedStyle(node);if(!r.width||!r.height||style.display==='none'||style.visibility==='hidden'||Number(style.opacity)===0)return false;for(let p=node.parentElement;p&&p!==document.body;p=p.parentElement){const s=getComputedStyle(p);if(s.display==='none'||s.visibility==='hidden'||Number(s.opacity)===0)return false;}return true;}
function candidates(){const out=[];for(const node of document.querySelectorAll('img,[style],[class*="terrain"],[class*="tile"]')){if(host?.contains(node)||!visible(node))continue;const style=getComputedStyle(node),r=node.getBoundingClientRect();let source,background=false;if(node.tagName==='IMG')source=sourceUrl(node.currentSrc||node.src);else{const match=style.backgroundImage.match(/^url\(["']?(.+?)["']?\)$/);if(match){source=sourceUrl(match[1]);background=true;}}if(!source)continue;const filename=new URL(source).pathname.split('/').pop();if(!source.includes('/ani/')&&!unitPattern.test(source)&&filename!=='terrain_spritesheet.png'&&!/^(neutral|orangestar|greenearth|bluemoon).*\.gif$/i.test(filename))continue;out.push({node,r,style,source,background,kind:unitPattern.test(source)?'unit':'terrain'});}return out;}
function filters(node,root){const list=[];let opacity=1;for(let n=node;n;n=n.parentElement){const style=getComputedStyle(n);opacity*=Number(style.opacity);if(style.filter!=='none')list.push(style.filter);if(n===root)break;}return{opacity,filter:list.join(' ')};}
function normalizedCss(value,node){const factor=16/(parseFloat(node.style.width)||16);return value.replace(/(-?\d+(?:\.\d+)?)px/g,(_,n)=>`${Number(n)*factor}px`);}
function visibleGameState(root,width,height){
 const result={readOnly:true,canSendOrders:false,viewerPlayerId:null,currentPlayerId:null,units:[]};
 try{const viewer=typeof window.getViewerPId==='function'?window.getViewerPId():window.viewerPId;result.viewerPlayerId=Number.isInteger(Number(viewer))&&Number(viewer)>0?Number(viewer):null;result.currentPlayerId=Number.isInteger(Number(window.currentTurn))&&Number(window.currentTurn)>0?Number(window.currentTurn):null;const fog=document.querySelector('#fog-canvas'),fogCtx=fog?.getContext('2d');
 for(const span of root.querySelectorAll('.game-unit[data-unit-id]')){if(!visible(span))continue;const unit=window.unitsInfo?.[span.dataset.unitId];if(!unit)continue;const x=Number(unit.units_x),y=Number(unit.units_y),id=Number(unit.units_id),owner=Number(unit.units_players_id);if(![id,owner,x,y].every(Number.isInteger)||x<0||y<0||x>=width||y>=height)continue;
 let z=0;for(let n=span;n&&n!==root;n=n.parentElement){const value=getComputedStyle(n).zIndex;if(value!=='auto'){z=Number(value)||0;break;}}
 if(fogCtx&&visible(fog)&&z<104){try{if(fogCtx.getImageData(x*16+8,y*16+8,1,1).data[3]>0)continue;}catch{continue;}}
 const numeric=(value,max)=>value!==null&&value!==undefined&&value!==''&&Number.isFinite(Number(value))&&Number(value)>=0&&Number(value)<=max?Number(value):null;
 const name=typeof unit.units_name==='string'&&/^[A-Za-z .-]{1,24}$/.test(unit.units_name)?unit.units_name:'Visible unit';
 result.units.push({id,owner,x,y,name,hp:numeric(unit.units_hit_points,10),fuel:numeric(unit.units_fuel,999),ammo:numeric(unit.units_ammo,99),spent:unit.units_moved===1});
 }
 }catch{/* Missing globals leave unit details unavailable, not guessed. */}
 return result;
}
function officialFrame(){
 const root=document.querySelector('#gamemap'),ground=document.querySelector('canvas#map-background');
 if(!root||!ground)return null;
 if(!ground.width||!ground.height||ground.width%16||ground.height%16)throw new Error('Unexpected AWBW terrain canvas dimensions.');
 const width=ground.width/16,height=ground.height/16;if(width>128||height>128)throw new Error('AWBW map is too large.');
 const canvas=document.createElement('canvas');canvas.width=ground.width;canvas.height=ground.height;const ctx=canvas.getContext('2d');ctx.imageSmoothingEnabled=false;
 const origin=ground.getBoundingClientRect(),sx=ground.width/origin.width,sy=ground.height/origin.height;
 function zIndex(node){for(let n=node;n&&n!==root;n=n.parentElement){const z=getComputedStyle(n).zIndex;if(z!=='auto')return Number(z)||0;}return 0;}
 const nodes=[...root.querySelectorAll('canvas,img')].filter(n=>visible(n)&&(!n.closest('.unit-options-game,.build-options-game')||n===ground)).sort((a,b)=>zIndex(a)-zIndex(b));
 for(const node of nodes){const r=node.getBoundingClientRect();if(node.tagName==='IMG'&&(!node.complete||!node.naturalWidth))continue;const effect=filters(node,root);ctx.globalAlpha=effect.opacity;ctx.filter=effect.filter||'none';try{ctx.drawImage(node,(r.left-origin.left)*sx,(r.top-origin.top)*sy,r.width*sx,r.height*sy);}catch{}}
 const frame=canvas.toDataURL('image/png');if(frame.length>4000000)throw new Error('Rendered map exceeds snapshot size limit.');
 return{format:'field-command-snapshot-v2',gameId:new URL(location.href).searchParams.get('games_id'),title:`AWBW #${new URL(location.href).searchParams.get('games_id')}`,day:Number(document.body.innerText.match(/\bDay\s+(\d+)/i)?.[1])||null,game:visibleGameState(root,width,height),capturedAt:new Date().toISOString(),map:{width,height,tileSize:16,layers:[],frame},coverage:{renderedOnly:true,warning:'Read-only pixel mirror of the original map canvas, fog, and visible sprites. Game orders remain in AWBW.'}};
}
function snapshot(){const official=officialFrame();if(official)return official;const all=candidates();if(all.length<12)throw new Error('Not enough rendered map sprites found. Let the map finish loading.');const groups=new Map();for(const c of all){let parent=c.node.parentElement;for(let d=0;parent&&d<7;d++,parent=parent.parentElement){if(parent===document.body||parent===document.documentElement)break;const r=parent.getBoundingClientRect();if(r.width<100||r.height<80||r.width>3000||r.height>3000)continue;if(!groups.has(parent))groups.set(parent,[]);groups.get(parent).push(c);}}
let best=null,score=0;for(const[node,items]of groups){if(items.length<12)continue;const r=node.getBoundingClientRect();const widths=items.map(c=>Math.round(c.r.width));const counts=new Map();widths.forEach(w=>counts.set(w,(counts.get(w)||0)+1));const tile=[...counts].sort((a,b)=>b[1]-a[1])[0][0];if(tile<8||tile>128)continue;const cells=r.width*r.height/(tile*tile);const density=Math.min(1,items.length/Math.max(1,cells));const value=items.length*(.25+density);if(value>score){score=value;best={node,items,tile};}}
if(!best)throw new Error('Could not identify a map container. Export inspection so the adapter can be adjusted.');
const {items,tile}=best,left=Math.min(...items.map(c=>c.r.left)),top=Math.min(...items.map(c=>c.r.bottom))-tile;
const layers=items.map(c=>{const effect=filters(c.node,best.node);return{x:Math.round((c.r.left-left)/tile),y:Math.round((c.r.bottom-top)/tile)-1,source:c.source,kind:c.kind,width:c.r.width/tile*16,height:c.r.height/tile*16,background:c.background,backgroundPosition:normalizedCss(c.style.backgroundPosition,c),backgroundSize:normalizedCss(c.style.backgroundSize,c),opacity:effect.opacity,filter:effect.filter,locator:{tag:c.node.tagName,id:c.node.id.slice(0,80),classes:String(c.node.className||'').slice(0,120)}};}).filter(l=>l.x>=0&&l.y>=0);
const width=Math.max(...layers.map(l=>l.x))+1,height=Math.max(...layers.map(l=>l.y))+1;if(width>128||height>128)throw new Error('Detected map is too large; original page structure needs inspection.');
const gameId=new URL(location.href).searchParams.get('games_id');if(!/^\d+$/.test(gameId||''))throw new Error('This is not a game page.');const text=document.body.innerText,day=Number(text.match(/\bDay\s+(\d+)/i)?.[1])||null;
return{format:'field-command-snapshot-v1',gameId,title:`AWBW #${gameId}`,day,capturedAt:new Date().toISOString(),map:{width,height,tileSize:tile,layers},coverage:{renderedOnly:true,warning:'Rendered sprites only. Terrain meaning, HP, ownership, fog rules, and server turn state are not yet verified.'}};}
function download(data,name){const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),10000);}
async function inspect(){status.textContent='Preparing read-only inspection…';const resources=[...new Set([...document.querySelectorAll('script[src],link[rel="stylesheet"]')].map(n=>n.src||n.href).filter(u=>path(u)&&/\.(js|css)(?:\?|$)/i.test(u)))].slice(0,30),publicFiles=[];let total=0;for(const url of resources){try{const p=path(url),response=await originalFetch.call(window,new URL(p,location.origin),{credentials:'omit',signal:AbortSignal.timeout(10000)});if(!response.ok||path(response.url)!==p||!/(javascript|ecmascript|text\/css)/i.test(response.headers.get('content-type')||''))continue;const text=await response.text();if(/^\s*<(?:!doctype|html)/i.test(text))continue;if(text.length>2000000||total+text.length>8000000)continue;total+=text.length;publicFiles.push({path:p,source:text});}catch{/* Report absent files, never retry with session credentials. */}}
let state=null,error='';try{state=snapshot();}catch(e){error=e.message;}const metadata={format:'field-command-inspection-v2',snapshot:state,snapshotError:error,capturedAt:new Date().toISOString(),contracts:contracts.slice().map((c,i)=>({...c,responseSample:i>=contracts.length-20?c.responseSample:null})),publicFiles,pageStructure:{scripts:resources.map(path),mapCandidateCount:candidates().length},note:'Only whitelisted game/action sample values are included. Authentication values, arbitrary strings, headers, cookies, HTML, and inline scripts are excluded. Samples are evidence from the official client, not independent verification. Public static source files were requested without credentials.'};download(metadata,`awbw-inspection-${new URL(location.href).searchParams.get('games_id')}.json`);status.textContent=`Inspection exported. ${publicFiles.length} public source files; ${contracts.length} observed requests.${error?' Map adapter: '+error:''}`;}
function sendSnapshot(){if(!client||client.closed){connected=false;return;}try{const data=snapshot(),signature=JSON.stringify({...data,capturedAt:''});if(signature!==lastSent){client.postMessage({type:'FC_SNAPSHOT',snapshot:data},clientOrigin);lastSent=signature;}status.textContent=`Read-only mirror: ${data.map.width}×${data.map.height}. Keep this AWBW tab open.`;lastError='';}catch(e){if(e.message!==lastError){status.textContent=e.message;lastError=e.message;}}}
window.addEventListener('message',event=>{if(event.source!==client||event.origin!==clientOrigin||event.data?.type!=='FC_READY')return;connected=true;lastSent='';sendSnapshot();});
function openClient(){let existing='';try{existing=localStorage.getItem('field-command-client-url')||'';}catch{}const input=prompt('Paste your Field Command site URL. Use its deployed HTTPS address, or http://localhost:5173 for local development.',existing);if(!input)return;try{const url=new URL(input);if(url.protocol!=='https:'&&!(url.protocol==='http:'&&['localhost','127.0.0.1'].includes(url.hostname)))throw new Error('Use HTTPS, or localhost for development.');url.pathname=url.pathname.replace(/(?:play|index|bridge)\.html$/,'');if(!url.pathname.endsWith('/'))url.pathname+='/';const target=new URL('play.html?live=1',url);clientOrigin=target.origin;client=window.open(target.href,'field-command-live');if(!client)throw new Error('Allow this site to open the Field Command tab.');try{localStorage.setItem('field-command-client-url',url.href);}catch{}status.textContent='Opening Field Command. Keep this original tab open.';lastSent='';}catch(e){status.textContent=e.message;}}
function mount(){if(document.getElementById('fc-bridge-tool'))return;host=document.createElement('div');host.id='fc-bridge-tool';host.style.cssText='position:fixed;left:12px;bottom:12px;z-index:2147483645;max-width:calc(100vw - 24px)';ui=host.attachShadow({mode:'open'});ui.innerHTML='<style>details{font:12px system-ui;color:#edf2d8;background:#1b2e45;border:1px solid #95b6c5;border-radius:8px;max-width:335px;padding:12px;box-shadow:0 4px 25px #0005}summary{cursor:pointer;font-weight:bold;color:#f5dd91}p{line-height:1.6}button{font:inherit;min-height:44px;background:#e7da9b;color:#1b3144;border:0;border-radius:4px;padding:10px;margin:4px;cursor:pointer}button:disabled{opacity:.5}#status{font-size:11px;overflow-wrap:anywhere}</style><details><summary>Field Command · Read-only bridge</summary><p>Mirrors the visible battlefield to your Field Command site. This tool never sends game orders.</p><button id="open">Open handheld view</button><button id="snapshot">Export snapshot</button><button id="inspect">Export inspection</button><p id="status" role="status">Use the official AWBW page normally to observe its requests. No need to take extra game actions for collection. Export inspection when ready.</p></details>';document.body.append(host);status=ui.querySelector('#status');ui.querySelector('#open').onclick=openClient;ui.querySelector('#snapshot').onclick=()=>{try{download(snapshot(),`awbw-snapshot-${new URL(location.href).searchParams.get('games_id')}.json`);status.textContent='Snapshot exported.';}catch(e){status.textContent=e.message;}};ui.querySelector('#inspect').onclick=async()=>{ui.querySelector('#inspect').disabled=true;try{await inspect();}catch(e){status.textContent=e.message;}finally{ui.querySelector('#inspect').disabled=false;}};timer=setInterval(()=>{if(connected)sendSnapshot();},1500);observer=new MutationObserver(()=>{if(!connected)return;clearTimeout(window.__fcBridgeDebounce);window.__fcBridgeDebounce=setTimeout(sendSnapshot,500);});observer.observe(document.body,{childList:true,subtree:true,attributes:true,attributeFilter:['src','style','class']});window.addEventListener('pagehide',()=>{clearInterval(timer);observer.disconnect();});}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',mount,{once:true});else mount();
})();
