export function mountLobby(css) {
 const origin=location.origin;
 const parse=doc=>{const found=new Map();for(const a of doc.querySelectorAll('a[href]')){try{const u=new URL(a.getAttribute('href'),origin),id=u.searchParams.get('games_id');if(u.origin!==origin||u.pathname!=='/game.php'||!/^\d+$/.test(id||''))continue;let name=a.textContent.trim().replace(/\s+/g,' ');if(!name||/^(view|play|game|\d+)$/i.test(name))name=`Game #${id}`;if(!found.has(id))found.set(id,{id,name,url:u.href});}catch{}}return [...found.values()];};
 function mount(){
  const overflow=document.body.style.overflow;document.body.style.overflow='hidden';
  let viewport=document.querySelector('meta[name="viewport"]'),madeViewport=!viewport,oldViewport=viewport?.getAttribute('content');if(!viewport){viewport=document.createElement('meta');viewport.name='viewport';document.head.append(viewport);}viewport.content='width=device-width,initial-scale=1,viewport-fit=cover';
  const host=document.createElement('div');host.id='fc-lobby';host.style.cssText='position:fixed;inset:0;z-index:2147483640;overflow:auto;background:#182338';const root=host.attachShadow({mode:'open'});
  const style=document.createElement('style');style.textContent=css+'\n:host{font:14px monospace;color:#e5ecd0}.lobby{max-width:680px;margin:0 auto;padding:20px}.lobby h1{font-size:24px;color:#f4d981}.games{display:grid;gap:12px;margin:20px 0}.game-link{display:block;color:#e5ecd0;border:2px solid #789b77;border-radius:6px;padding:18px;text-decoration:none;background:#203746;min-height:44px}.game-link strong{display:block;font-size:18px;margin:8px 0}.game-link small{color:#acd57e}.actions{display:flex;gap:14px;flex-wrap:wrap}.actions a{color:#f4d981;min-height:44px}.actions button{font:inherit;color:#e5ecd0;background:#263d49;border:1px solid #789b77;padding:10px;min-height:44px}';root.append(style);
  const panel=document.createElement('main');panel.className='lobby';panel.innerHTML='<header class="game-header"><div class="game-logo">FIELD<span>COMMAND</span></div><span>AWBW</span></header><h1>Choose your battlefield</h1><p>Your AWBW account · Your multiplayer games</p><div class="actions"><button id="refresh">Refresh games</button><a href="/">Account & lobby ↗</a><button id="original">Original AWBW</button></div><p id="status" role="status">Reading your game list…</p><div class="games" id="games"></div>';root.append(panel);document.body.append(host);
  const message=root.querySelector('#status'),list=root.querySelector('#games');let generation=0;
  function show(games,turns){list.replaceChildren();for(const game of games){const a=document.createElement('a');a.className='game-link';a.href=`${origin}/game.php?games_id=${game.id}`;const badge=document.createElement('small');badge.textContent=turns?.has(game.id)?'▶ YOUR TURN':turns?'WAITING':'AWBW GAME';const title=document.createElement('strong');title.textContent=game.name;const label=document.createElement('span');label.textContent=`#${game.id} · Open battlefield →`;a.append(badge,title,label);list.append(a);}message.textContent=games.length?`${games.length} games${turns?` · ${games.filter(g=>turns.has(g.id)).length} awaiting your move`:''}`:'No games found. Use Account & lobby to sign in or check your AWBW account.';}
  async function read(url){const response=await fetch(url,{credentials:'same-origin',signal:AbortSignal.timeout(15000)});if(!response.ok||new URL(response.url).origin!==origin||new URL(response.url).pathname!=='/yourgames.php')throw new Error('Open AWBW to sign in, then return to Your Games.');return parse(new DOMParser().parseFromString(await response.text(),'text/html'));}
  async function refresh(){const g=++generation;message.textContent='Reading your game list…';const [all,turn]=await Promise.allSettled([read('/yourgames.php'),read('/yourgames.php?yourTurn=1')]);if(g!==generation)return;show(all.status==='fulfilled'?all.value:parse(document),turn.status==='fulfilled'?new Set(turn.value.map(v=>v.id)):null);if(all.status==='rejected')message.textContent=all.reason.message;}
  root.querySelector('#refresh').onclick=refresh;root.querySelector('#original').onclick=()=>{generation++;host.remove();document.body.style.overflow=overflow;if(madeViewport)viewport.remove();else if(oldViewport===null)viewport.removeAttribute('content');else viewport.content=oldViewport;};refresh();
 }
 if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',mount,{once:true});else mount();
}
