/* Bundled with styles.css into a self-contained userscript. */
(() => {
'use strict';
if(window.top!==window.self||document.getElementById('fc-root'))return;
if(location.pathname!=='/yourgames.php')return;
const origin=location.origin;
const escape=value=>String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function gameUrl(href){try{const url=new URL(href,origin),id=url.searchParams.get('games_id');if(url.origin!==origin||url.pathname!=='/game.php'||!/^\d+$/.test(id||''))return null;return{id,url:`${origin}/game.php?games_id=${id}`};}catch{return null;}}
function parseGames(doc){const found=new Map();for(const anchor of doc.querySelectorAll('a[href]')){const ref=gameUrl(anchor.getAttribute('href'));if(!ref)continue;let label=anchor.textContent.trim().replace(/\s+/g,' ');if(!label||/^(view|join|play|game|open|\d+)$/i.test(label))label=anchor.querySelector('img')?.alt?.trim()||`Operation #${ref.id}`;const existing=found.get(ref.id);if(!existing||(existing.name.startsWith('Operation #')&&!label.startsWith('Operation #')))found.set(ref.id,{...ref,name:label});}return[...found.values()];}
const originalOverflow=document.body.style.overflow;
const root=document.createElement('div');root.id='fc-root';
root.innerHTML=`<div class="app-shell"><aside class="sidebar"><a class="brand" href="${origin}/yourgames.php"><span class="brand-mark">F<span>↗</span></span><span>FIELD<br>COMMAND<span class="brand-caption">YOUR AWBW. RECONSIDERED.</span></span></a><div class="workspace-label">YOUR HEADQUARTERS</div><nav aria-label="Main navigation"><button class="nav-item active" data-fc="dashboard"><span>▦</span> Operations</button><button class="nav-item" data-fc="manual"><span>◈</span> Field manual</button><a class="nav-item" href="${origin}/"><span>↗</span> AWBW account & lobby</a></nav><div class="sidebar-bottom"><div class="demo-note"><span class="signal-dot"></span> AWBW SESSION<p>Connected on AWBW's own domain.</p></div><button class="profile" data-fc="exit"><span class="avatar">AW</span><span>Original AWBW<span class="muted profile-sub">Return to the standard interface</span></span><span class="profile-arrow">↗</span></button></div></aside><main><header class="topbar"><span class="breadcrumb">Headquarters <span>/</span> <strong id="fc-breadcrumb">Operations</strong></span><div class="header-right"><span class="demo-badge">AWBW HARNESS</span><button class="button secondary" data-fc="exit">Original AWBW ↗</button></div></header><section class="page" id="fc-page"></section><footer class="mobile-nav"><button class="active" data-fc="dashboard">▦<span>Operations</span></button><button data-fc="refresh">↻<span>Refresh</span></button><button data-fc="exit">↗<span>Original</span></button></footer></main></div>`;
const css=document.createElement('style');css.textContent=FIELD_COMMAND_CSS+'\n#fc-root{position:fixed;inset:0;z-index:2147483000;overflow:auto;background:var(--bg);color:var(--text);font:14px Inter,ui-sans-serif,system-ui,sans-serif;line-height:normal;text-align:left}#fc-root a{text-decoration:none}#fc-root .sidebar{top:0;left:0}#fc-root h1,#fc-root h2,#fc-root h3{color:var(--text)}#fc-root .fc-game-frame{width:100%;height:calc(100dvh - 250px);min-height:400px;border:1px solid var(--border);border-radius:8px;background:white}#fc-root .fc-live-mark{background:radial-gradient(ellipse at 30% 30%,#425d37,#202e24);color:#c2ed78;font-size:30px}#fc-root .fc-source{font-size:10px;color:var(--muted)}#fc-root .fc-error{color:#f5a56e;line-height:1.7;font-size:13px}#fc-root .fc-toolbar{display:flex;gap:10px;flex-wrap:wrap;margin-top:20px}#fc-root .header-right .button{font-size:10px;padding:8px 12px;min-height:32px}@media(max-width:760px){#fc-root .topbar{padding:0 15px}#fc-root .demo-badge{display:none}}';document.head.append(css);document.body.append(root);document.body.style.overflow='hidden';
const panel=root.querySelector('#fc-page');let games=[],filter='all',loading=false,error='',current=null,turnKnown=false,request=0;
function dashboard(){current=null;root.querySelector('#fc-breadcrumb').textContent='Operations';const count=games.filter(g=>g.turn).length;panel.innerHTML=`<div class="page-heading"><div><div class="eyebrow"><span class="signal-dot"></span> YOUR EXISTING AWBW SESSION</div><h1>Your next move.</h1><p class="subtitle">Your real games. A clearer field.</p></div><a class="button primary" href="${origin}/">AWBW lobby ↗</a></div><div class="overview"><div><span class="stat-label">AWAITING YOUR ORDERS</span><strong>${loading?'…':turnKnown?String(count).padStart(2,'0'):'—'}<span class="stat-dot"></span></strong><span class="stat-detail">${turnKnown?'Reported by AWBW':'Turn status unavailable'}</span></div><div><span class="stat-label">LISTED OPERATIONS</span><strong>${loading?'…':String(games.length).padStart(2,'0')}</strong><span class="stat-detail">From your AWBW game list</span></div><div class="overview-note"><span class="compass">✳</span><div><span class="stat-label">SAME BACKEND</span><p>Your account.<br>Your games. Your orders.</p></div></div></div><div class="section-heading"><div class="tabs"><button class="tab ${filter==='all'?'active':''}" data-filter="all">All operations</button><button class="tab ${filter==='turn'?'active':''}" data-filter="turn" ${turnKnown?'':'disabled'}>Your turn <span>${turnKnown?count:'—'}</span></button></div><button class="text-button" data-fc="refresh">↻ Refresh</button></div>${error?`<p class="fc-error" role="alert">${escape(error)}</p>`:''}<div class="game-list">${loading?'<div class="empty" role="status">Reading your AWBW games…</div>':cards()}</div><div class="bottom-note"><span>✧</span> Reads AWBW pages. Game actions use the original AWBW interface.</div>`;}
function cards(){const visible=games.filter(g=>filter==='all'||g.turn);if(!visible.length)return`<div class="info-card"><h2>${filter==='turn'?'No games awaiting your turn.':'No game links found.'}</h2><p>${filter==='turn'?'AWBW did not list any games in its Your Turn filter.':'Check that you are signed in on AWBW. If games appear in the original page, its HTML may not match this adapter.'}</p><button class="button secondary" data-fc="exit">View original page ↗</button></div>`;return visible.map(g=>`<article class="game-card"><div class="map-preview fc-live-mark" aria-hidden="true">▦<span class="map-coordinate">AWBW / OPERATION ${escape(g.id)}</span></div><div class="card-content"><div class="card-top"><span class="status-pill ${g.turn?'':'waiting'}">${g.turn?'● YOUR TURN':turnKnown?'◷ NOT YOUR TURN':'AWBW OPERATION'}</span><span class="card-time">#${escape(g.id)}</span></div><div class="card-middle"><div><h2>${escape(g.name)}</h2><span class="fc-source">Live AWBW game link</span></div><button class="open-game" data-game="${escape(g.id)}" aria-label="Open ${escape(g.name)}"><svg viewBox="0 0 24 24" width="18" height="18" aria-hidden="true"><path d="M6 18 18 6M6 6h12v12" fill="none" stroke="currentColor" stroke-width="1.5"/></svg></button></div><div class="card-bottom"><span class="co-avatar">AW</span><span>Uses your existing account</span><a class="day-badge" href="${escape(g.url)}">OPEN FULL PAGE ↗</a></div></div></article>`).join('');}
async function readPage(path){const response=await fetch(new URL(path,origin),{credentials:'same-origin',signal:AbortSignal.timeout(20000)});if(!response.ok)throw new Error(`AWBW returned HTTP ${response.status}.`);const final=new URL(response.url);if(final.origin!==origin||final.pathname!=='/yourgames.php')throw new Error('AWBW redirected away from Your Games. Sign in on the original page first.');return new DOMParser().parseFromString(await response.text(),'text/html');}
async function refresh(){const token=++request;loading=true;error='';dashboard();try{const allDoc=await readPage('/yourgames.php');const all=parseGames(allDoc);let ids=new Set(),known=false,turnError='';try{const turnDoc=await readPage('/yourgames.php?yourTurn=1');ids=new Set(parseGames(turnDoc).map(g=>g.id));known=true;}catch(e){turnError='Game list loaded, but turn status could not be read. '+e.message;}if(token!==request)return;turnKnown=known;error=turnError;games=all.map(g=>({...g,turn:ids.has(g.id)}));}catch(e){if(token!==request)return;error='Could not read your AWBW game list. '+e.message;games=[];turnKnown=false;}loading=false;if(!current)dashboard();}
function openGame(game){current=game;root.querySelector('#fc-breadcrumb').textContent='Battlefield';panel.innerHTML=`<button class="text-button" data-fc="dashboard">← All operations</button><div class="battle-heading"><div><div class="eyebrow">ORIGINAL AWBW GAME CONTROLS</div><h1>${escape(game.name)}</h1><p class="subtitle">#${escape(game.id)} · Your real game on AWBW</p></div><a class="button secondary" href="${escape(game.url)}">Full page ↗</a></div><p class="fc-source">Moves and end-turn actions inside this frame affect your actual AWBW game. The battlefield is AWBW’s original UI.</p><iframe class="fc-game-frame" title="AWBW game ${escape(game.id)}" src="${escape(game.url)}"></iframe><div class="fc-toolbar"><a class="text-button" href="${escape(game.url)}">If the game cannot load in a frame, open the full page ↗</a></div>`;root.scrollTo({top:0});}
root.addEventListener('click',event=>{const button=event.target.closest('[data-fc],[data-game],[data-filter]');if(!button)return;if(button.dataset.game){const game=games.find(g=>g.id===button.dataset.game);if(game)openGame(game);return;}if(button.dataset.filter){filter=button.dataset.filter;dashboard();return;}switch(button.dataset.fc){case'exit':++request;root.remove();css.remove();document.body.style.overflow=originalOverflow;break;case'refresh':refresh();break;case'dashboard':if(!games.length&&!loading)refresh();else dashboard();break;case'manual':current={manual:true};root.querySelector('#fc-breadcrumb').textContent='Field manual';panel.innerHTML='<div class="eyebrow">FIELD MANUAL</div><h1>Same game. Clearer view.</h1><div class="info-card"><h2>Your account stays on AWBW</h2><p>The harness reads your existing game list and AWBW’s Your Turn filter using same-origin requests. It never asks for your password or sends your session to another service.</p><h2>Playing</h2><p>Open an operation to play through the original AWBW controls inside a frame. These are real multiplayer actions. Use Full Page if the game blocks framing or you prefer the original layout.</p><h2>Current scope</h2><p>The dashboard is redesigned. The battlefield and order controls are still the original AWBW interface. This adapter has been tested against representative HTML fixtures; live compatibility needs validation.</p></div>';break;}});
refresh();
})();
