import {createPractice,unitAt,reachable,targets,order,buy,endTurn,stats} from './tactics.js';
import {validateSnapshot} from './snapshot.js';
const bridgePeer=(window.FC_EMBEDDED||new URLSearchParams(location.search).has('embedded'))?window.parent:window.opener;
const $=s=>document.querySelector(s),SAVE='field-command-practice-v1';
let state=createPractice(),catalog=[],assetPaths=new Map(),selected=null,destination=null,phase='select',cursor={x:3,y:5},scale=innerWidth>=900?3:2,snapshot=null,live=false,sound=false,audio;
try{const saved=JSON.parse(localStorage.getItem(SAVE));if(saved?.format==='field-command-practice-v1'&&saved.width===18&&saved.height===14&&saved.terrain.length===252&&Array.isArray(saved.units))state=saved;}catch{/* Storage is optional. */}
let capabilities=null,livePlan=null,liveRequest=null,liveWaiting=false,liveSelection=null,bridgeSeen=0;
function ordersReady(){return live&&snapshot&&acceptLive&&capabilities?.gameId===snapshot.gameId&&capabilities.available&&Date.now()-bridgeSeen<6000&&!liveWaiting;}
function bridgePost(data){bridgePeer?.postMessage({...data,gameId:snapshot?.gameId},'https://awbw.amarriner.com');}
function requestPlan(input){if(!ordersReady()){message(capabilities?.reason||'The AWBW bridge is not ready for orders.');return;}liveRequest=crypto.randomUUID();livePlan=null;liveSelection=input;bridgePost({type:'FC_PLAN',requestId:liveRequest,input});message('Checking this preview with AWBW’s rules…');render();}
function commitLive(choice){if(!ordersReady()||!livePlan)return;const token=livePlan.token;liveRequest=crypto.randomUUID();liveWaiting=true;livePlan=null;bridgePost({type:'FC_COMMIT',requestId:liveRequest,token,choice:choice.key});render();message('Sending through AWBW…');}
function clearLive(){capabilities=null;livePlan=null;liveRequest=null;liveWaiting=false;liveSelection=null;}
function save(){if(snapshot)return;try{localStorage.setItem(SAVE,JSON.stringify(state));}catch{message('Practice continues; browser storage is unavailable.');}}
function message(text){$('#message').textContent=text;}
function beep(){if(!sound)return;try{audio??=new AudioContext();audio.resume();const o=audio.createOscillator(),g=audio.createGain();o.type='square';o.frequency.value=440;g.gain.value=.015;o.connect(g).connect(audio.destination);o.start();o.stop(audio.currentTime+.045);}catch{/* Audio is optional. */}}
function asset(name){return catalog.find(a=>new URL(a.source).pathname.endsWith('/'+name))?.file;}
function img(file,cls=''){const image=document.createElement('img');image.src=file;image.alt='';image.className=cls;return image;}
function tileArt(tile){if(tile.type==='water')return {crop:[48,0]};if(tile.type==='forest')return {crop:[32,0]};if(tile.type==='mountain')return {crop:[16,0]};if(tile.type==='road')return {crop:[224,0]};if(['city','base'].includes(tile.type)){const army=tile.owner==='os'?'orangestar':tile.owner==='ge'?'greenearth':'neutral';return {file:asset(`${army}${tile.type}.gif`)||asset(`neutral${tile.type}.gif`)};}return {file:asset('plain.gif')};}
function appendArt(cell,tile){const plain=asset('plain.gif');if(plain)cell.append(img(plain));const art=tileArt(tile);if(art.file&&art.file!==plain)cell.append(img(art.file));if(art.crop){const span=document.createElement('span');span.className='crop';span.style.backgroundImage=`url("${asset('terrain_spritesheet.png')}")`;span.style.backgroundPosition=`-${art.crop[0]}px -${art.crop[1]}px`;cell.append(span);}}
function renderMap(){const width=snapshot?snapshot.map.width:state.width,height=snapshot?snapshot.map.height:state.height,grid=$('#map');grid.style.setProperty('--cols',width);grid.style.setProperty('--tile',`${16*scale}px`);grid.style.setProperty('--scale',scale);grid.replaceChildren();grid.style.backgroundImage=snapshot?.map.frame?`url("${snapshot.map.frame}")`:'';grid.style.backgroundSize=snapshot?.map.frame?`${width*16*scale}px ${height*16*scale}px`:'';const unit=state.units.find(u=>u.id===selected),available=snapshot&&livePlan?.kind==='unit'?new Map(livePlan.reachable.map(n=>[`${n%snapshot.map.width},${Math.floor(n/snapshot.map.width)}`,true])):!snapshot&&phase==='move'&&unit?reachable(state,unit):new Map(),attackable=!snapshot&&phase==='attack'&&unit?targets(state,unit,destination?.x??unit.x,destination?.y??unit.y):[];const layerMap=new Map();if(snapshot)for(const l of snapshot.map.layers){const key=`${l.x},${l.y}`;if(!layerMap.has(key))layerMap.set(key,[]);layerMap.get(key).push(l);}
for(let y=0;y<height;y++)for(let x=0;x<width;x++){const cell=document.createElement('button');cell.className='map-cell';cell.setAttribute('role','gridcell');cell.setAttribute('aria-label',`Tile ${x+1}, ${y+1}`);cell.dataset.x=x;cell.dataset.y=y;cell.tabIndex=x===cursor.x&&y===cursor.y?0:-1;if(x===cursor.x&&y===cursor.y)cell.classList.add('cursor');if(snapshot){if(available.has(`${x},${y}`))cell.classList.add('reachable');if(livePlan?.path?.includes(y*width+x))cell.classList.add('path-preview');const layers=layerMap.get(`${x},${y}`)||[];if(snapshot.map.frame)cell.classList.add('raster');else if(!layers.length)cell.classList.add('unknown');for(const l of layers){const file=assetPaths.get(new URL(l.source).pathname);if(!file){cell.classList.add('unknown');continue;}const span=document.createElement(l.background?'span':'img');span.className='live-layer'+(l.kind==='unit'?' unit':'');span.style.width=`${l.width}px`;span.style.height=`${l.height}px`;span.style.opacity=l.opacity;span.style.filter=l.filter;if(l.background){span.style.backgroundImage=`url("${file}")`;span.style.backgroundPosition=l.backgroundPosition||'0px 0px';span.style.backgroundSize=l.backgroundSize||'auto';}else{span.src=file;span.alt='';}cell.append(span);}}
else{appendArt(cell,state.terrain[y*width+x]);const occupant=unitAt(state,x,y);const show=occupant&&!(destination&&occupant.id===selected&&(destination.x!==x||destination.y!==y));if(show)appendUnit(cell,occupant);if(destination&&selected&&(destination.x!==unit?.x||destination.y!==unit?.y)&&destination.x===x&&destination.y===y&&unit)appendUnit(cell,unit);if(available.has(`${x},${y}`))cell.classList.add('reachable');if(attackable.some(t=>t.x===x&&t.y===y))cell.classList.add('target');}cell.onclick=()=>tap(x,y);grid.append(cell);}
$('#coords').textContent=`FIELD ${String(cursor.x+1).padStart(2,'0')} : ${String(cursor.y+1).padStart(2,'0')}`;$('#zoom-label').textContent=`${scale}×`;}
function appendUnit(cell,unit){const file=asset(`${unit.army}${unit.type}.gif`);if(file)cell.append(img(file,'unit'+(unit.spent?' spent':'')));const hp=document.createElement('span');hp.className='health';hp.textContent=unit.hp<10?unit.hp:'';cell.append(hp);}
function command(label,fn,primary=false,disabled=false){const b=document.createElement('button');b.textContent=label;b.disabled=disabled;b.className=primary?'primary':'';b.onclick=()=>{beep();try{fn();}catch(e){message(e.message);}};$('#commands').append(b);}
function render(){renderMap();const commands=$('#commands');commands.replaceChildren();$('#terrain-preview').replaceChildren();$('#terrain-preview').style.backgroundImage='';$('#mode').textContent=snapshot?(live?(capabilities?.enabled&&snapshot.game?'AWBW · LIVE ORDERS':'AWBW · LIVE READ-ONLY'):'AWBW · SNAPSHOT'):'LOCAL PRACTICE';$('#operation').textContent=snapshot?snapshot.title:'RIVER CROSSING';$('#army').textContent=snapshot?'AWBW BATTLEFIELD':state.army==='os'?'ORANGE STAR':'GREEN EARTH';$('.commander-bar').classList.toggle('green',!snapshot&&state.army==='ge');$('#portrait').src=asset(snapshot?'smallandy.png':state.army==='os'?'smallandy.png':'smalljess.png')||asset('smallandy.png');$('#portrait').classList.toggle('hidden',!!snapshot);$('#day').textContent=`DAY ${snapshot?snapshot.day??'—':String(state.day).padStart(2,'0')}`;$('#funds').textContent=snapshot?(snapshot.game?.funds!=null?`${snapshot.game.funds.toLocaleString()} G`:'READ-ONLY'):`${state.funds[state.army].toLocaleString()} G`;$('#end-turn').disabled=!!snapshot&&!ordersReady();$('#end-turn').textContent=snapshot?'End AWBW turn →':'End practice turn →';$('#original-game').classList.toggle('hidden',!snapshot);if(snapshot)$('#original-game').href=`https://awbw.amarriner.com/game.php?games_id=${snapshot.gameId}`;
if(snapshot){$('#terrain-name').textContent='AWBW BATTLEFIELD';if(snapshot.map.frame){const preview=$('#terrain-preview'),size=preview.clientWidth;preview.style.backgroundImage=`url("${snapshot.map.frame}")`;preview.style.backgroundSize=`${snapshot.map.width*size}px ${snapshot.map.height*size}px`;preview.style.backgroundPosition=`-${cursor.x*size}px -${cursor.y*size}px`;}const visible=snapshot.game?.units.find(u=>livePlan?.kind==='unit'?u.id===livePlan.unitId:u.x===cursor.x&&u.y===cursor.y);$('#unit-name').textContent=visible?visible.name:ordersReady()?'Choose your next order':'Battlefield view';$('#unit-stats').textContent=visible?`HP ${visible.hp??'—'}/10 · Fuel ${visible.fuel??'—'} · Ammo ${visible.ammo??'—'} · ${visible.spent?'Acted':'Not marked moved'}`:snapshot.map.frame?'Swipe to pan · Use + / − to zoom.':'Grey tiles have no captured sprite.';$('#phase').textContent=liveWaiting?'WAITING FOR AWBW':ordersReady()?(livePlan?.summary||'SELECT YOUR UNIT OR PROPERTY'):'READ-ONLY FIELD VIEW';$('#sync-status').textContent=live?(capabilities?.enabled?'AWBW SESSION · LIVE ORDERS':'LIVE DOM MIRROR · NO ORDERS'):'IMPORTED SNAPSHOT · NO ORDERS';
 if(livePlan&&ordersReady()){
  for(const choice of livePlan.choices)command(choice.label,()=>commitLive(choice),true);
  if(livePlan.kind==='unit'&&livePlan.x===undefined)command('Stay here',()=>requestPlan({kind:'unit',unitId:livePlan.unitId,x:livePlan.from.x,y:livePlan.from.y}),true);
  if(!livePlan.choices.length&&livePlan.kind==='build')command('No affordable units',()=>{},false,true);
  command('Cancel preview',cancel);
 }else if(ordersReady())command('Select a ready unit or property',()=>{},false,true);
 command('AWBW controls ↗',()=>{if(live)bridgePost({type:'FC_CLOSE'});else window.open($('#original-game').href,'_blank','noopener');});return;}
$('#sync-status').textContent='PRACTICE RULES · SAVED LOCALLY';const tile=state.terrain[cursor.y*state.width+cursor.x],unit=state.units.find(u=>u.id===selected)||unitAt(state,cursor.x,cursor.y);appendArt($('#terrain-preview'),tile);$('#terrain-name').textContent=tile.type.toUpperCase();$('#unit-name').textContent=unit?`${unit.army.toUpperCase()} ${unit.type.toUpperCase()}`:tile.type==='base'?'Deployment base':'Select a unit';$('#unit-stats').textContent=unit?`HP ${unit.hp}/10 · Move ${stats[unit.type].move} · ${unit.spent?'Orders complete':'Ready'}`:tile.type==='city'?`Capture points ${tile.capture}/20`:'Tap a unit to inspect and give orders.';$('#phase').textContent=({select:'SELECT A UNIT',move:'CHOOSE DESTINATION',command:'ISSUE AN ORDER',attack:'SELECT A TARGET'})[phase];
if(phase==='select'){if(unit&&unit.army===state.army&&!unit.spent)command('Move',()=>{selected=unit.id;phase='move';render();message('Choose a highlighted tile. B cancels.');},true);else if(!unit&&tile.type==='base'&&tile.owner===state.army)for(const type of ['infantry','tank'])command(`Buy ${type} · ${stats[type].cost.toLocaleString()} G`,()=>{buy(state,cursor.x,cursor.y,type);save();render();message(`${type} deployed. It can act next turn.`);},false,state.funds[state.army]<stats[type].cost);else command('Select a ready unit',()=>{},false,true);}
if(phase==='move')command('Stay here',()=>{destination={x:unit.x,y:unit.y};phase='command';render();},true);
if(phase==='command'&&unit){command('Wait',()=>commit('wait'),true);command('Attack',()=>{phase='attack';render();message('Choose a red-marked adjacent enemy.');},false,!targets(state,unit,destination.x,destination.y).length);const t=state.terrain[destination.y*state.width+destination.x];command('Capture',()=>commit('capture'),false,unit.type!=='infantry'||!['city','base'].includes(t.type)||t.owner===unit.army);command('Cancel',cancel);}
if(phase==='attack')command('Cancel attack',()=>{phase='command';render();});}
function commit(action,target){order(state,selected,destination,action,target);selected=null;destination=null;phase='select';save();render();message(state.log[0]);}
function tap(x,y){cursor={x,y};beep();if(snapshot){
 if(ordersReady()){
  if(liveSelection?.kind==='unit'&&livePlan?.reachable.includes(y*snapshot.map.width+x)){requestPlan({kind:'unit',unitId:liveSelection.unitId,x,y});return;}
  const u=snapshot.game?.units.find(u=>u.x===x&&u.y===y),b=snapshot.game?.buildings.find(b=>b.x===x&&b.y===y);
  if(u?.owner===snapshot.game.viewerPlayerId&&!u.spent){requestPlan({kind:'unit',unitId:u.id});return;}
  if(!u&&b?.owner===snapshot.game?.viewerPlayerId){requestPlan({kind:'build',x,y});return;}
 }
 render();message(liveWaiting?'Waiting for AWBW’s result.':capabilities?.reason||`Visible tile ${x+1}, ${y+1}. Open this game in Field Command to give orders.`);return;}
const unit=state.units.find(u=>u.id===selected);if(phase==='move'){if(reachable(state,unit).has(`${x},${y}`)){destination={x,y};phase='command';render();message('Preview only. Choose Wait, Attack, or Capture to commit.');}else{render();message('That tile is outside this unit’s movement range.');}return;}if(phase==='attack'){const enemy=unitAt(state,x,y);try{commit('attack',enemy?.id);}catch(e){render();message(e.message);}return;}if(phase==='command'){render();return;}selected=unitAt(state,x,y)?.id??null;render();}
function cancel(){if(live){bridgePost({type:'FC_CANCEL'});livePlan=null;liveSelection=null;}selected=null;destination=null;phase='select';render();message(snapshot?(liveWaiting?'Order already sent. Waiting for AWBW.':'Preview cancelled. No order sent.'):'Order cancelled. No unit has moved.');}
$('#cancel').onclick=cancel;$('#select').onclick=()=>tap(cursor.x,cursor.y);$('#menu-open').onclick=()=>$('#game-menu').showModal();$('#menu-close').onclick=()=>$('#game-menu').close();$('#end-turn').onclick=()=>{if(snapshot){requestPlan({kind:'end'});$('#game-menu').close();return;}endTurn(state);selected=null;destination=null;phase='select';save();render();$('#game-menu').close();message(state.log[0]);};$('#reset').onclick=()=>{clearLive();acceptLive=false;snapshot=null;live=false;state=createPractice();cursor={x:3,y:5};selected=null;destination=null;phase='select';save();render();$('#game-menu').close();message('New local practice match.');};$('#sound').onclick=()=>{sound=!sound;$('#sound').textContent=`Sound: ${sound?'on':'off'}`;beep();};$('#fullscreen').onclick=async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await document.documentElement.requestFullscreen();}catch{message('Full screen is unavailable in this browser.');}};
function center(){const cell=$(`#map [data-x="${cursor.x}"][data-y="${cursor.y}"]`),scroll=$('#map-scroll');if(cell){const r=cell.getBoundingClientRect(),s=scroll.getBoundingClientRect();scroll.scrollTo({left:scroll.scrollLeft+r.left-s.left-scroll.clientWidth/2+r.width/2,top:scroll.scrollTop+r.top-s.top-scroll.clientHeight/2+r.height/2});}}$('#center').onclick=center;function zoom(delta){scale=Math.max(1,Math.min(4,scale+delta));renderMap();center();}$('#zoom-in').onclick=()=>zoom(1);$('#zoom-out').onclick=()=>zoom(-1);
function move(dx,dy){const width=snapshot?snapshot.map.width:state.width,height=snapshot?snapshot.map.height:state.height;cursor.x=Math.max(0,Math.min(width-1,cursor.x+dx));cursor.y=Math.max(0,Math.min(height-1,cursor.y+dy));render();center();}document.querySelectorAll('[data-dir]').forEach(b=>b.onclick=()=>move(...({up:[0,-1],down:[0,1],left:[-1,0],right:[1,0]})[b.dataset.dir]));window.addEventListener('keydown',e=>{if($('#game-menu').open)return;const delta={ArrowUp:[0,-1],ArrowDown:[0,1],ArrowLeft:[-1,0],ArrowRight:[1,0]}[e.key];if(delta){e.preventDefault();move(...delta);}else if(e.key.toLowerCase()==='a'||e.key==='Enter')$('#select').click();else if(e.key.toLowerCase()==='b'||e.key==='Escape')cancel();});
function loadSnapshot(data,isLive=false){const validated=validateSnapshot(data),same=isLive&&live&&snapshot?.gameId===validated.gameId;snapshot=validated;live=isLive;if(!same){clearLive();cursor={x:0,y:0};selected=null;destination=null;phase='select';}cursor.x=Math.min(cursor.x,snapshot.map.width-1);cursor.y=Math.min(cursor.y,snapshot.map.height-1);render();if(same)return;const missing=new Set(snapshot.map.layers.filter(l=>!assetPaths.has(new URL(l.source).pathname)).map(l=>l.source)).size;message(`AWBW #${snapshot.gameId}: ${snapshot.map.frame?'complete rendered frame':snapshot.map.layers.length+' visible sprite layers'}. ${missing?`${missing} source sprites unavailable in this pack. `:''}${snapshot.coverage.warning||'Rendered DOM only; no orders are sent.'}`);}
$('#snapshot-input').onchange=async e=>{const file=e.target.files[0];if(!file)return;try{if(file.size>10*1024*1024)throw new Error('Snapshot exceeds 10 MB.');loadSnapshot(JSON.parse(await file.text()));acceptLive=false;$('#game-menu').close();}catch(error){message(error.message);}e.target.value='';};
let ready=false,acceptLive=(window.FC_EMBEDDED===true||new URLSearchParams(location.search).has('live'));window.addEventListener('message',event=>{
 if(!ready||!acceptLive||event.origin!=='https://awbw.amarriner.com'||event.source!==bridgePeer)return;
 const data=event.data;if(!data||typeof data!=='object')return;
 try{
  if(data.type==='FC_SNAPSHOT'){loadSnapshot(data.snapshot,true);return;}
  if(!live||!snapshot)return;
  if(data.type==='FC_CAPABILITIES'){
   if(data.gameId!==snapshot.gameId)return;
   bridgeSeen=Date.now();if(JSON.stringify(capabilities)===JSON.stringify(data))return;capabilities=data;
   if(livePlan&&(data.revision!==livePlan.revision||!data.enabled||data.locked)){livePlan=null;message('AWBW state changed. Select a fresh preview.');}
   render();return;
  }
  if(data.requestId!==liveRequest)return;
  if(data.type==='FC_PLAN_RESULT'){
   if(data.plan){livePlan=data.plan;if(liveSelection?.kind==='end'&&livePlan.choices[0]){commitLive(livePlan.choices[0]);return;}message(data.plan.summary+'. Choose an order.');}
   else{livePlan=null;message(data.message||'Preview unavailable.');}
   render();
  }else if(data.type==='FC_ORDER_RESULT'){
   if(data.status!=='sent'){liveWaiting=false;livePlan=null;liveSelection=null;}
   render();message(data.message||'Check the original AWBW page.');
  }
 }catch(e){message('Bridge message rejected: '+e.message);}
});
setInterval(()=>{if(live&&capabilities?.available&&Date.now()-bridgeSeen>=6000){capabilities={...capabilities,available:false,reason:'AWBW tab is inactive or disconnected. Return to it to reconnect.'};livePlan=null;render();message(capabilities.reason);}},1500);
async function init(){try{if(window.FC_CATALOG)catalog=window.FC_CATALOG.assets;else{const response=await fetch('assets/catalog.json');if(!response.ok)throw new Error('Sprite pack unavailable.');catalog=(await response.json()).assets;}assetPaths=new Map(catalog.map(a=>[new URL(a.source).pathname,a.file]));render();center();ready=true;if((window.FC_EMBEDDED===true||new URLSearchParams(location.search).has('live'))){message('Waiting for the AWBW bridge. Keep the original game tab open.');bridgePeer?.postMessage({type:'FC_READY'},'https://awbw.amarriner.com');}}catch(e){message('Could not start battlefield: '+e.message);}}init();
