// Local practice rules. This module is never used to submit AWBW orders.
export const stats={infantry:{move:3,attack:35,cost:1000},tank:{move:6,attack:60,cost:7000},artillery:{move:4,attack:50,cost:6000}};
const costs={infantry:{plain:1,forest:1,mountain:2,road:1,city:1,base:1,water:Infinity},tank:{plain:1,forest:2,mountain:Infinity,road:1,city:1,base:1,water:Infinity},artillery:{plain:1,forest:2,mountain:Infinity,road:1,city:1,base:1,water:Infinity}};
export function createPractice(){const width=18,height=14;const terrain=Array.from({length:width*height},(_,i)=>{const x=i%width,y=Math.floor(i/width);let type='plain';if(x===8||x===9)type='water';if(y===6)type='road';if((x<7||x>10)&&((x*7+y*3)%13<3))type='forest';if((x<6||x>11)&&y>8&&(x+y)%7===0)type='mountain';return{type,owner:null,capture:20};});const set=(x,y,type,owner=null)=>terrain[y*width+x]={type,owner,capture:20};set(2,5,'base','os');set(15,7,'base','ge');set(4,4,'city','os');set(5,8,'city');set(12,4,'city');set(13,9,'city','ge');set(8,6,'road');set(9,6,'road');return{format:'field-command-practice-v1',width,height,terrain,units:[{id:'os1',x:3,y:5,type:'infantry',army:'os',hp:10,spent:false},{id:'os2',x:4,y:6,type:'tank',army:'os',hp:10,spent:false},{id:'os3',x:2,y:8,type:'infantry',army:'os',hp:10,spent:false},{id:'ge1',x:11,y:6,type:'tank',army:'ge',hp:10,spent:false},{id:'ge2',x:12,y:5,type:'infantry',army:'ge',hp:10,spent:false},{id:'ge3',x:14,y:9,type:'infantry',army:'ge',hp:10,spent:false}],day:1,army:'os',funds:{os:10000,ge:10000},log:['Practice operation started. Local rules; no AWBW orders.']};}
export function unitAt(state,x,y){return state.units.find(u=>u.x===x&&u.y===y);}
export function reachable(state,unit){if(unit.spent||unit.army!==state.army)return new Map();const visited=new Map([[`${unit.x},${unit.y}`,0]]),queue=[[unit.x,unit.y,0]];while(queue.length){queue.sort((a,b)=>a[2]-b[2]);const[x,y,d]=queue.shift();if(d!==visited.get(`${x},${y}`))continue;for(const[dx,dy]of[[1,0],[-1,0],[0,1],[0,-1]]){const nx=x+dx,ny=y+dy;if(nx<0||ny<0||nx>=state.width||ny>=state.height)continue;const occupant=unitAt(state,nx,ny);if(occupant&&occupant.id!==unit.id)continue;const cost=costs[unit.type]?.[state.terrain[ny*state.width+nx].type]??Infinity;const nd=d+cost,key=`${nx},${ny}`;if(nd<=stats[unit.type].move&&nd<(visited.get(key)??Infinity)){visited.set(key,nd);queue.push([nx,ny,nd]);}}}return visited;}
export function targets(state,unit,x=unit.x,y=unit.y){return state.units.filter(u=>u.army!==unit.army&&Math.abs(u.x-x)+Math.abs(u.y-y)===1);}
export function order(state,id,destination,action,targetId){const unit=state.units.find(u=>u.id===id);if(!unit||unit.spent||unit.army!==state.army)throw new Error('This unit cannot act.');const{x,y}=destination;if(!reachable(state,unit).has(`${x},${y}`))throw new Error('Destination is not reachable.');const tile=state.terrain[y*state.width+x];let target;if(action==='attack'){target=targets(state,unit,x,y).find(t=>t.id===targetId);if(!target)throw new Error('Target is not adjacent.');}else if(action==='capture'){if(unit.type!=='infantry'||!['city','base'].includes(tile.type)||tile.owner===unit.army)throw new Error('This property cannot be captured.');}else if(action!=='wait')throw new Error('Unknown order.');unit.x=x;unit.y=y;unit.spent=true;if(action==='attack'){const damage=Math.max(1,Math.round(stats[unit.type].attack*unit.hp/100));target.hp=Math.max(0,target.hp-damage);if(target.hp>0)unit.hp=Math.max(0,unit.hp-Math.max(1,Math.round(stats[target.type].attack*target.hp/200)));state.units=state.units.filter(u=>u.hp>0);state.log.unshift(`${unit.type} attacked: ${damage} damage in practice rules.`);}else if(action==='capture'){tile.capture-=unit.hp;if(tile.capture<=0){tile.owner=unit.army;tile.capture=20;state.log.unshift('Property captured.');}else state.log.unshift(`Capturing property: ${tile.capture} points remain.`);}else state.log.unshift(`${unit.type} moved and waited.`);state.log=state.log.slice(0,8);}
export function buy(state,x,y,type){if(!stats[type])throw new Error('Unknown unit.');const tile=state.terrain[y*state.width+x];if(tile?.type!=='base'||tile.owner!==state.army||unitAt(state,x,y))throw new Error('Choose an empty friendly base.');if(state.funds[state.army]<stats[type].cost)throw new Error('Insufficient funds.');state.funds[state.army]-=stats[type].cost;state.units.push({id:`built-${state.day}-${state.units.length}-${Date.now()}`,x,y,type,army:state.army,hp:10,spent:true});state.log.unshift(`${type} deployed.`);}
export function endTurn(state){const army=state.army==='os'?'ge':'os';state.army=army;if(army==='os')state.day++;state.units.forEach(u=>{if(u.army===army)u.spent=false;});const income=state.terrain.filter(t=>t.owner===army).length*1000;state.funds[army]+=income;state.log.unshift(`${army==='os'?'Orange Star':'Green Earth'} turn. Income ${income} G.`);}
